defaults:
  - _self_

num_train_frames: 500000
stddev_schedule: 'linear(1.0,0.1,250000)'
nstep: 1
show_train_stats_every_frames: 2000
lr: 3e-4
replay_buffer_size: 1_000_000
offline: True
domain_name: reacher
task_name: easy
train_context_name: ...
test_context_name: ...
offline_dir: ...
